### ISSUE TITLE
Remove duplication of documentation (HTML and wiki)

### ISSUE THREAD

**Issue by mmurdoch** [mmurdoch/arduinounit#1]
The HTML documentation is not rendered by github and the wiki content is currently still on googlecode (http://code.google.com/p/arduinounit/ and http://code.google.com/p/arduinounit/w/list).

Possible approaches:
- transfer googlecode wiki content to github wiki and delete HTML
- convert HTML documentation to markdown so that it will display in github (don't transfer googlecode wiki)
- transfer googlecode wiki content to github pages and delete HTML

**Comment by wmacevoy** [comment]
Done (a long time ago).
