### ISSUE TITLE
Test failures are reported in reverse order in version 1.7

### ISSUE THREAD

**Issue by mmurdoch** [mmurdoch/arduinounit#17]
Before version 1.7 test failures were reported in the order they appeared in the test sketch. This changed in 1.7 where they are reported in reverse order.

**Comment by matthijskooijman** [comment]
Actually, the initialization order is guaranteed to be top-to-bottom within a single translation unit (e.g. a .cpp file, or all .ino files combined). See #3 at http://en.cppreference.com/w/cpp/language/initialization#Dynamic_initialization or https://stackoverflow.com/a/7222755/740048

Reverting to the previous behaviour might not be so bad, or perhaps adding a "sort by name" flag could give the best of both worlds?

**Comment by wmacevoy** [comment]
2.0 has been out long enough that this would be a breaking change.  The list of tests is generated before the setup function is called, and made alphabetical.  Changing this leads to a chicken-egg problem of which setup would actually sort them, and still leads to non-deterministic problems for projects spread among multiple files.  If you want to control the order, you can prefix the tests with a numbering scheme: t01_config, t02_io, etc.

**Comment by matthijskooijman** [comment]
Oh, right, setting a "do not sort" config in setup() is too late, so that won't work. Oh well, sorting isn't really bad anyway.

**Comment by wmacevoy** [comment]
1.7 is no longer supported
