### ISSUE TITLE
Arduino 2.0 gives progmem warnings on compilation

### ISSUE THREAD

**Issue by mmurdoch** [mmurdoch/arduinounit#20]
During compilation with the Arduino IDE version 1.0.3 the following warning is output a number of times (formatted here for clarity):

    <install_dir>\arduino-1.0.3\libraries\ArduinoUnit/ArduinoUnit.h: In static 
        member function 
            'static bool Test::assertion(const __FlashStringHelper*, 
                                         uint16_t, 
                                         const __FlashStringHelper*, 
                                         const T&, 
                                         const __FlashStringHelper*, 
                                         bool (*)(const T&, const T&), 
                                         const __FlashStringHelper*, 
                                         const T&)':
    <install_dir>\arduino-1.0.3\libraries\ArduinoUnit/ArduinoUnit.h:485: 
        warning: only initialized variables can be placed into program 
                 memory area

**Comment by wmacevoy** [comment]
I think the IDE/avr-gcc versions have moved past this gcc bug.
