### ISSUE TITLE
Standardize in-line documentation style between versions

### ISSUE THREAD

**Issue by mmurdoch** [mmurdoch/arduinounit#22]
The codebases for both 1.x and 2.x contain in-line API documentation but they use different markup. Both styles should be able to be processed by doxygen (or equivalent) but it would be good to be consistent.

**Comment by wmacevoy** [comment]
This is a really old thread now.  I thought 1.x didn't use doxygen, so I never looked at the convention and just wrote doxygen-style comments in the 2.x base.  Is there a point to not closing this issue?

**Comment by mmurdoch** [comment]
Agreed. There is no point to not close this issue :)

Closing...
