### ISSUE TITLE
Commonalize FakeStream and FakeStreamBuffer

### ISSUE THREAD

**Issue by mmurdoch** [mmurdoch/arduinounit#33]
`FakeStreamBuffer` extends `FakeStream` but only provides the ability to add multiple bytes to the stream in a single function call. It would be nice to move this extra functionality down into `FakeStream` to simplify usage of the library (perhaps also deprecating `FakeStreamBuffer`?) We would also need to check the impact of doing this on the code size of sketches currently using `FakeStream`.

**Comment by wmacevoy** [comment]
[v2.3.7-alpha] MockStream  now has the functionality of FakeStream see the mockstream example.
