### ISSUE TITLE
Change FakeStreamBuffer to use a String internally

### ISSUE THREAD

**Issue by mmurdoch** [mmurdoch/arduinounit#34]
`FakeStreamBuffer` uses a linked list to store bytes which can be read. The implementation could be significantly simplified by reusing the Arduino `String` class for this purpose.

**Comment by wmacevoy** [comment]
I think both these will be deprecated; they are not well documented features of the testing framework.

**Comment by wmacevoy** [comment]
v2.3.7-alpha now has MockPrint and MockStream, with an example in mockstream and some documentation in the README.  Please use these instead.
