### ISSUE TITLE
RFE: Custom messages on assertions

### ISSUE THREAD

**Issue by m-mcgowan** [mmurdoch/arduinounit#35]
For example:

        for (int i=0; i<count;i++) {
            assertEqual(buf[i],read[i]) << "at index " << i;
        }        

This is inspired by the << operator available on assertions in [Google Test](https://code.google.com/p/googletest/wiki/Primer#Assertions).

**Comment by wmacevoy** [comment]
Ok - I'm closing this discussion.  I don't know how to do this without wasting a lot of cpu time.
