### ISSUE TITLE
Submit library to Library Manager

### ISSUE THREAD

**Issue by ffissore** [mmurdoch/arduinounit#40]
Since version 1.6.2, Arduino has a built in Library Manager, a graphical interface for one click installing libraries. It would be nice to have ArduinoUnit listed. This repo looks already ok, it just needs a tag. See https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by mmurdoch** [comment]
Created [release 2.1.1](https://github.com/mmurdoch/arduinounit/releases/tag/v2.1.1) which includes the `library.properties` file required for Library Manager integration.

**Comment by ffissore** [comment]
Lib now listed. Thanks! :)
