### ISSUE TITLE
Add tolerance for double comparison

### ISSUE THREAD

**Issue by DanNixon** [mmurdoch/arduinounit#44]
Doubles should really be compared using a tolerance, this is my current work around:

```cpp
void assertClose(double a, double b, double tol = 0.01)
{
  assertTrue(abs(a - b) < tol);
}
```

**Comment by wmacevoy** [comment]
Try branch iss44 and see if you like the version.  I created an assertClose which allows for relative and absolute errors, and prints the arguments if the assertion fails.  Note assertEqual is not changed.

**Comment by wmacevoy** [comment]
I think your macro would be better as

assertLess(abs(b-a),tol)

because it would report the error amount if it failed.

**Comment by wmacevoy** [comment]
I'm closing this issue, the assertLess above works well and avoids assumptions about tolerance.
