### ISSUE TITLE
Assert equal doesn't work

### ISSUE THREAD

**Issue by gokhandilek** [mmurdoch/arduinounit#49]
I am trying to write some tests that I want it to fail but it appears I cannot get the tests to fail.
It passes even if I return an integer other than 0.

```
void MoveTest:: moveUpUnit() {
 for (int i=0; i<100; i++){
 box.slideUp(0);
 assertEqual(0, box.totalSlide());
 }
}

```

**Comment by wmacevoy** [comment]
We have certainly tested that assertequal works correctly for a variety of cases, including zero.  Can you provide more context for the code snippet?  The best would be a buildable case that fails on uno/mega without additional special hardware.

Warren MacEvoy
wmacevoy@coloradomesa.edu
http://www.coloradomesa.edu/~wmacevoy
970-248-1070
