### ISSUE TITLE
Feature Request: Get this library/framework to work on the ESP8266 arduino platform

### ISSUE THREAD

**Issue by crankyoldgit** [mmurdoch/arduinounit#55]
Hi, I'd love to use this unit testing framework, but I develop for the ESP8266 platform using the [arduino framework](https://github.com/esp8266/Arduino). This software bombs out as per Issue #54.

Any chance we could get some official support or help porting this across? We don't appear to have any unit testing framework available. Not having unit tests makes me a sad panda.

Thanks in advance.

**Comment by wmacevoy** [comment]
[thread summary] ArduinoUnit 2.3.5-alpha now supports flash string de-duplication on AVR and uses RAM on other platforms, along with a number of memory-saving optimizations that do not change the outcome of tests. It also supports ESP 8266 and ESP 32 platforms (along with development platform "en vitro" tests). Please try the latest pre-release and provide feedback on #73 if you are interested in these features.
