### ISSUE TITLE
Test::exclude isn't working properly. Test::exclude("*");

### ISSUE THREAD

**Issue by gtame** [mmurdoch/arduinounit#72]
Hi ,
if the first exclude sentence is  Test::exclude("*").  The sentence doesn't work.

![error](https://user-images.githubusercontent.com/5931355/37558702-52336750-2a18-11e8-8c15-ec6e2b1085d2.png)

`
#include "main.h"
 
test(correct)
{
	int x=1;
	assertEqual(x,1);
}

test(incorrect)
{
	int x=1;
	assertNotEqual(x,1);
}

test(otro)
{
	int x=1;
	assertNotEqual(x,1);
}

extern "C" void __cxa_pure_virtual() {}

int main() {

	init();
	setup();
         while (true)
	loop();
}

void setup()
{
	Serial.begin(9600);
	while(!Serial)
	
	Test::exclude("*");
	Test::include("incorrect");
}

void loop() 
{ 
	Test::run();
}
`
However if I added before another exclude sentence works. Ej, Test::exclude("*e")
 
`void setup()
{
	Serial.begin(9600);
	while(!Serial)

 	Test::exclude("*e");
	Test::exclude("*");
	Test::include("incorrect");
 
}`

![ok](https://user-images.githubusercontent.com/5931355/37558742-0a18bce4-2a19-11e8-87be-c5b25cf6f157.png)

**Comment by wmacevoy** [comment]
There needs to be a ';' after the `while (!Serial)`, perhaps preferably `while (!Serial) { /* busy */ }` -- the line after the while (exclude) was never executed.  Pretty subtle; sorry C syntax got you there...

**Comment by gtame** [comment]
Hi, it's clear. A tree didn't let me to see the forest😀
