### ISSUE TITLE
Review Guidebook

### ISSUE THREAD

**Issue by wmacevoy** [mmurdoch/arduinounit#79]
Would anyone mind reading over the tutorial?  (@matthijskooijman @bxparks @ianfixes in particular, since you have used the framework a lot):

https://github.com/mmurdoch/arduinounit/blob/master/guidebook.md

Thanks!

**Comment by ianfixes** [comment]
Seems to have more philosophy in it than instruction.  Presumably someone is already sold on the idea of unit testing if they're looking at a GitHub repo that enables unit testing.  

So for my money, the tutorial really "starts" at the "Making a reliable thing" section.

I'd also recommend turning the code in the tutorial (that first listing in particular) on its head.  You have `test` and `testing`, followed by `TestSetup` and `IdiotSetup`, and by that point (as an unfamiliar reader) I'm not sure what all these names are accomplishing.  If you read from the bottom up, it's more clear: you take your usual Arduino `setup` and `loop` functions, and add some test hooks to them.  Still, it's not clear where `Test::run()` comes in from and `test(WaterSensorConnected)` / ``testing(WaterSensorSane)` are never explained.  

Am I missing something?  All in all I think it would benefit from establishing a clear audience and goal, and working from there. Example outline:

> This tutorial is for people who know how to use Arduino and want to write unit tests; I will show you how to do that using this library.

> At a high level, `arduinounit` works by __________.  You need to ______ in the setup, and _____ in the loop.  The macros ________ have been defined to make this easier.

> Here's an example of the simplest possible test with the least amount of added code

> Here's how you run that test

> Here's what it looks like when it fails

> Here's an example of 2 things being tested at once

> Here's how you run it and tell which test failed

> (the rest of your examples)

**Comment by wmacevoy** [comment]
I agree it suffers from a mixed message.  The readme has a quickstart and a this-is-that reference.  Maybe it should be called a guidebook.  I wanted to write something an early programmer (that does not know about objects or testing or words like functional programming or stateless design or mocking) can see the value of testing and specifics of what it might mean to write tests and how they are useful.

**Comment by mMerlin** [comment]
The information for an beginning programmer is good stuff, but it should not be called a tutorial.

The tutorial (or guidebook) should show how to get things done, not why you should want to do them.

The zen of testing?

**Comment by wmacevoy** [comment]
Thanks for the help.  I renamed it a guide book and added some getting started information.  It also made me change the API (assertNear and optional return values) to make the flow of testing easier.  It is getting clear this is really a 3.0 release; there are a lot of upgrades.

**Comment by wmacevoy** [comment]
@mMerlin : I took your name.  Probably helps that I'm writing it from Nepal.

**Comment by soundanalogous** [comment]
> Presumably someone is already sold on the idea of unit testing if they're looking at a GitHub repo that enables unit testing

Just to add my 2 cents here as well. I would not agree with the above statement. It's reasonable that someone may be interested in testing but not fully sold on the idea of unit testing, especially for an embedded systems platform like Arduino, so a little philosophy up front doesn't hurt.

This is a great guide BTW. Thanks @wmacevoy for putting it together!

**Comment by matthijskooijman** [comment]
I had a quick read up to "step 1", this indeed looks helpful. Here's some initial comments, more when I find time to read the rest.

Under "What" you have a list of things to test, but some of those seem like things to assert during normal program execution, not so much to test during unit testing.

> assertRelation(between [,foot << note [,retva]])

The "between" is a bit confusing here, since it later turns into 2 or 3 arguments?

> assertRelation(a,b) or assertTestStatus(testName)

 Perhaps these should be separate bullet points, so the latter can be explained a bit more verbosely?

**Comment by wmacevoy** [comment]
Ok fixed the format a little.  The guidebook is about testing, not just unit testing. AU facilitates many kinds of tests.

**Comment by wmacevoy** [comment]
I moved the guidebook changes into the master branch.  It is pretty good now and can make changes without breaking anybody's builds.  Happy to take more suggestions...
