### ISSUE TITLE
Doesn't compile for Teensy 3.2 (release 3.0.2)

### ISSUE THREAD

**Issue by ssilverman** [mmurdoch/arduinounit#87]
The error message:
> src/ArduinoUnitUtility/ArduinoUnitMockPrint.cpp:136:95: error: no matching function for call to 'MockPrint::concat(const char*, size_t&)'

**Comment by ssilverman** [comment]
My fix in `ArduinoUnitMockPrint.cpp`:

```c++
size_t MockPrint::write(const uint8_t *buffer, size_t size) {
#ifdef TEENSYDUINO
  append((const char *)buffer, size);
#else
  concat((const char *)buffer, size);
#endif
  return size;
}
```

**Comment by wmacevoy** [comment]
I'm looking at the teensy source,

https://github.com/PaulStoffregen/cores/blob/master/teensy/Print.h

And see no concat.  What method are you mocking?

**Comment by wmacevoy** [comment]
Sorry took a bit to think about what this was doing.  Can you make a Pull Request & I will encorporate your change?

**Comment by ssilverman** [comment]
#88

**Comment by dogweather** [comment]
@wmacevoy Thanks for merging this! Would you consider cutting a new release so we can use it easily in the Arduino IDE?

**Comment by wmacevoy** [comment]
3.0.3+ has the merge.
